apiVersion: apps/v1
kind: Deployment
metadata:
  name: aztegiveaway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aztegiveaway
  template:
    metadata:
      labels:
        app: aztegiveaway
    spec:
      containers:
        - name: aztegiveaway
          image: europe-west1-docker.pkg.dev/aztegiveaway/aztegiveaway-repo/aztegiveaway:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: aztegiveaway-secrets
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: aztegiveaway-secrets
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: aztegiveaway-secrets
                  key: SPRING_DATASOURCE_PASSWORD
            - name: BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: aztegiveaway-secrets
                  key: BOT_TOKEN
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: aztegiveaway-secrets
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: aztegiveaway-secrets
                  key: MYSQL_DATABASE
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: aztegiveaway-secrets
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: aztegiveaway-secrets
                  key: MYSQL_PASSWORD
