apiVersion: v1
kind: Service
metadata:
  name: aztegiveaway
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: aztegiveaway
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-db
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mysql-db
  clusterIP: None
